### ISSUE TITLE
"used of closed network connection" error is encountered and execution is stopped

### ISSUE THREAD

**Issue by marius-uncrop** [getgauge/gauge-python#106]
### Description
From time to time, after some scenario fails, the remaining scenarios are skipped due to error "used of network connection"; the error is mostly encountered when the tests are running from jenkins.
Unfortunately, I cannot share the project i'm using and I wasn't able to replicate the issue yet with another smaller project.

Attached are  some logs that might help:
[jenkins.log](https://github.com/getgauge/gauge-python/files/2302533/jenkins.log)

### Other details:
* gauge -v
Gauge version: 1.0.0
Commit Hash: 5a99965

Plugins
-------
flash (0.0.1)
html-report (4.0.4)
python (0.3.3.nightly-2018-06-05)
screenshot (0.0.1)
spectacle (0.1.2)
xml-report (0.2.0)

*  python --version
Python 3.5.3

* pip3 show getgauge
Name: getgauge
Version: 0.3.3.dev20180605
Summary: Enables Python support for Gauge
Home-page: https://github.com/getgauge/gauge-python
Author: Gauge Team
Author-email: getgauge@outlook.com
License: MIT
Location: /home/marius/.local/lib/python3.5/site-packages
Requires: redBaron, protobuf, ptvsd, grpcio

* $ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"

**Comment by NivedhaSenthil** [comment]
We will try and check if we can reproduce the issue. Meanwhile it will be helpful if you can provide any particular scenario when this happens and from when this has started happening( if it had started happening after any particular nightly? ).

**Comment by NivedhaSenthil** [comment]
Tried couple of scenarios like with dataStore etc with same version of python and gauge in linux, did not encounter the error. Will be great if you can provide any sample to reproduce the issue.

**Comment by NivedhaSenthil** [comment]
Thanks for providing a sample. I could reproduce the error with it.. will pick up that on priority.

**Comment by marius-uncrop** [comment]
Initial tests look ok. i'll let you know if i notice similar problems.
thanks for the assistance

**Comment by sguptatw** [comment]
Closing this issue as it works with the given project. Please feel free to re-open it in case you find any related issue
```
Gauge version: 1.0.1.nightly-2018-08-28
Commit Hash: da2676b

Plugins
-------
python (0.3.4.nightly-2018-08-23)
```
