### ISSUE TITLE
gauge console output spamming HTTP request messages

### ISSUE THREAD

**Issue by TzurAnv** [getgauge/gauge-python#109]
### Description
the gauge output at the console spamming messages regarding the http activities
this does not occur running chrome driver outside the gauge framework

### Steps to reproduce
1. create any project using selenium
2. run the project using "gauge run"
3. a lot of console message output regarding http activity, such as:
http://127.0.0.1:47873 "POST /session/dff0fdabc0e774d8264e460e676a18f3/element/0.19401055944487688-2/value HTTP/1.1" 200 72
http://127.0.0.1:47873 "POST /session/dff0fdabc0e774d8264e460e676a18f3/element HTTP/1.1" 200 103

### Information that will help us debug

* Gauge version
Gauge version: 1.0.0
* Gauge Python plugin version
python (0.3.3)
* Python version
* `getgauge` package version, run `pip3 show getgauge` to get it
0.3.3
* OS information
ubunto 18

**Comment by zabil** [comment]
Related to https://github.com/getgauge/gauge-python/issues/91

This will be fixed in the next release of Gauge python

**Comment by TzurAnv** [comment]
i can confirm that the nightly build resolve this issue

**Comment by BugDiver** [comment]
@TzurAnv  Thanks for the confirmation. I'm closing this issue.

On another note, We have also released `gauge-python` with this fix.
