### ISSUE TITLE
gauge fail to take screenshot when running on a remote server

### ISSUE THREAD

**Issue by TzurAnv** [getgauge/gauge-python#111]
### Description
gauge fail to take screenshot when running on a remote server (for example selenium grid)
in my scenario i used docker based selenium grid containers with nodes
### Steps to reproduce
1. create a python-gauge selenium project 
2. make sure its working with remote driver
3. execute the scenario (make sure it will fail)
the report shows a screenshot from the local machine instead of the remote client executer

### Information that will help us debug

* Gauge version
1.0.0
* Gauge Python plugin version
0.3.3
* Python version
3.6.5
* `getgauge` package version, run `pip3 show getgauge` to get it
* OS information
ubunto 18

**Comment by zabil** [comment]
To handle this please implement a [custom screen shot handler](https://docs.gauge.org/latest/writing-specifications.html#taking-custom-screenshots).

```
from getgauge.python import screenshot
@screenshot
def take_screenshot():
    return driver.get_screenshot_as_base64()
```

Closing this as the default screenshot handler will not handle remote drivers. Please feel to comment here if you face any issues implementing custom screenshots.

**Comment by TzurAnv** [comment]
while trying to implement it im receiving the following error message:
TypeError: has type str, but expected one of: bytes

**Comment by zabil** [comment]
@TzurAnv can you share your implementation?

**Comment by TzurAnv** [comment]
@screenshot
def take_screenshot():
    return PageFactory.driver.get_screenshot_as_base64()

only the call for the driver is different, the error message is:
 TypeError: 'iVBORw0KGgoAAAANSUhEUgAABBAAAAbuCAYAAADjYsGwAAAgAElEQVR4nOzdd3gVVeLG8XduTS+EhBIIJfQmHURQpEsTQcDfKnb has type str, but expected one of: bytes

**Comment by sriv** [comment]
The screenshot should be a byte array, can you try something like this please:

```
@screenshot
def take_screenshot():
    return bytes(PageFactory.driver.get_screenshot_as_base64())
```

**Comment by TzurAnv** [comment]
now returning:
TypeError: string argument without an encoding

**Comment by sriv** [comment]
sorry, my python isn't very good.

You need to return a byte array equivalent of the string.

[`bytes`](https://docs.python.org/3/library/functions.html#func-bytes) is one way, so you need to pass `utf-8` as encoding.

alternatively I think you should be able to use `PageFactory.driver.get_screenshot_as_base64().encode()`, `encode` returns a byte array for me on python3.

**Comment by TzurAnv** [comment]
using PageFactory.driver.get_screenshot_as_base64().encode()
removing the error message but the report does not show the screenshot (just a broken image that doesnt shows anything when clicked on)

**Comment by surevs** [comment]
i tried setting up ```screenshot_on_failure = true``` in ``` env/default/default.properties ``` and screenshot is actually working fine on failure

**Comment by sriv** [comment]
@surevs - good catch, thanks.

I did not realize that `screenshot_on_failure` was [set to `false`](https://github.com/getgauge/gauge-repository/blob/master/templates/python_selenium/env/default/default.properties#L13) in `python_selenium` template.

**Comment by TzurAnv** [comment]
@surevs - the screenshot_on_failure was always true on my environment and i didn't saw the result as you showed above
did you try to run your code on a remote chrome driver server?

**Comment by surevs** [comment]
@TzurAnv The code has been executed on a local machine / chrome driver on MacOS ( it has worked the same way in windows too).
In order to handle the remote chrome driver ( a possible work around for the current scenario could be like this):
1. As you have rightly mentioned driver.get_screenshot_as_base64() to be appended into the scripts where ever applicable .
2. Once the screenshot is captured. You will need to get the base64 encoded string and convert into an image 
3. Once the conversion is done, we might store/save them into a new log directory or might need to tweak by extending the current html-report.

P.S:  In case you are using `pytest`. you can extend a custom method in `conftest.py`

**Comment by TzurAnv** [comment]
a workaround i thought it might help other of i share
using the web driver save screenshot method as we discussed does manage to capture to remote machine
so the following code managedto write the saved screenshot into the gauge report (in the case below for each step):

@after_step
def after_step():
    # Screenshots.capture_screenshot()
    if not os.path.exists(screenshot_directory):
        os.makedirs(screenshot_directory)
    datetime_now = str(int(datetime.datetime.now().strftime("%s")) * 1000)
    PageFactory.driver.save_screenshot(
        screenshot_directory+datetime_now+'.png')
    Messages.write_message(
        "<img src='../../../screenshots/" +
        datetime_now+".png' width='800' height='480'/>"

**Comment by PiotrNestor** [comment]
Just try according to the example. This just works when also using a remote WebDriver...
```
@custom_screen_grabber
def take_screenshot():
    return PageFactory.driver.get_screenshot_as_png()
```
