### ISSUE TITLE
execution hooks @before\after_scenario doesnt work if not in the same page as the other hook 

### ISSUE THREAD

**Issue by TzurAnv** [getgauge/gauge-python#113]
### Description
Add the expected behavior/issue description/Actual behavior here

### Steps to reproduce
1. created a page_factory model\class which containing all the hooks (after\before_suite and after\before scenario)
2. runs the project successfully 
3. move the after\before_suit hook function to another file
4. run the porject without the operation of the after\before_suits function

### Information that will help us debug

* Gauge version 
1.0.1
* Gauge Python plugin version
* Python version
0.3.4
* `getgauge` package version, run `pip3 show getgauge` to get it
0.3.4
* OS information
Ubuntu 18

**Comment by nehashri** [comment]
@TzurAnv I tried the above steps you have mentioned and it seems to work fine. Can you provide a sample project where you are able to replicate the issue.

**Comment by nehashri** [comment]
@TzurAnv I will be closing this issue. If you are still facing this, please reopen the issue
