### ISSUE TITLE
These messages did not appear under the step of executing the report

### ISSUE THREAD

**Issue by 0xNone** [getgauge/gauge-python#117]
### Description
These messages did not appear under the step of executing the report.
In the initialized code:
```python
@step("Vowels in English language are <vowels>.")
def assert_default_vowels(given_vowels):
    Messages.write_message("Given vowels are {0}".format(given_vowels))
    assert given_vowels == "".join(vowels)
```

![image](https://user-images.githubusercontent.com/16507416/47475093-af011d00-d84c-11e8-9fe6-4a66d9bd4320.png)

### Steps to reproduce
1. Initialize an project using the `gauge init python` command
2. This problem can occur using the `gauge run` command or the `gauge run specs/`

### Information that will help us debug
command: `pip3 show getgauge`
```
Name: getgauge
Version: 0.3.4
Summary: Enables Python support for Gauge
Home-page: https://github.com/getgauge/gauge-python
Author: Gauge Team
Author-email: getgauge@outlook.com
License: MIT
Location: /home/n0ne/.local/lib/python3.6/site-packages
Requires: six, redBaron, parso, protobuf, grpcio, ptvsd
```

command: `gauge -v`
```
Gauge version: 1.0.4
Commit Hash: 62b94b8

Plugins
-------
html-report (4.0.5)
python (0.3.4)
screenshot (0.0.1)
```

command: `python3.6 -V`
```
Python 3.6.5
```

command: `cat /etc/issue`
```
Ubuntu 18.04.1 LTS \n \l
```

**Comment by sguptatw** [comment]
@OxNone

Fix for this is available in 
```
Gauge version: 1.0.4.nightly-2018-10-23
Commit Hash: 62b94b8

Plugins
-------
html-report (4.0.6.nightly-2018-10-17)
```
The html-report plugin is yet to be released.

**Comment by sguptatw** [comment]
@0xNone

Html-report plugin is released. Kindly check with version https://github.com/getgauge/html-report/releases/tag/v4.0.6
