### ISSUE TITLE
Running the test gives the FileNotFoundError

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-python#120]
**Expected behavior**
Should not get error when running the specs

**Actual behavior**
Running the test gives the FileNotFoundError
> The tests are executed successfully though  
```
Traceback (most recent call last):
  File "check_and_install_getgauge.py", line 47, in <module>
    assert_versions()        
  File "check_and_install_getgauge.py", line 31, in assert_versions
    python_plugin_version = get_version()
  File "check_and_install_getgauge.py", line 11, in get_version
    proc = Popen(['gauge', '-v', '--machine-readable'], stdout=PIPE, stderr=PIPE)
  File "...\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 756, in __init__
    restore_signals, start_new_session)
  File "...\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 1155, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

**Steps to replicate**
* Create a new python project
`gauge init python`
* Run the specs
`gauge run`
> The run is successful. However the error message is printed

**Version**
```
Gauge version: 1.0.3
Commit Hash: ff6c0c3

Plugins
-------
python (0.3.5.nightly-2018-10-31)
```

Blocks #115

**Comment by NivedhaSenthil** [comment]
Seems to be working fine without any error with the above given steps. Is there anything else to be considered when running specs ? Tried on windows 10 and Python: 3.7.1

**Comment by sguptatw** [comment]
The issue seems to be on Windows. On Mac it is working as expected

**Comment by sguptatw** [comment]
**Findings**
On Windows, when gauge exe is used for installation, I do not face this issue. However when `npm install @getgauge/cli -g` is used to install gauge I am facing the above error.

**Comment by NivedhaSenthil** [comment]
This was happening due to https://bugs.python.org/issue17023. Fix done.
