### ISSUE TITLE
can't evaluate field Screenshot in type *generator.result

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-python#122]
**Expected behavior**
Should get the screenshot seamlessly

**Actual behavior**
Getting the error `[html-report]2018/11/29 11:32:00 template: Reports:234:35: executing "stepFailureDiv" at <.Screenshot>: can't evaluate field Screenshot in type *generator.result`

**Steps to replicate**
* Create a new `gauge-python` project
* Add step with implementation
```
@step("something")
def something():
    assert False, "Add implementation codesdfsdf"
```
* Use this in the spec
* Run the scenario from the **IDE**
> The above error occurs

**Version**
```
Gauge-VSCode - gauge-0.0.8.nightly-2018-11-27
Gauge version: 1.0.4.nightly-2018-11-26
Commit Hash: f6cb60c

Plugins
-------
python (0.3.5.nightly-2018-10-31)
```

**Comment by shubhamsc** [comment]
This issue was moved to getgauge/gauge-vscode#312
