### ISSUE TITLE
Gauge with pudb gives wrong terminal size

### ISSUE THREAD

**Issue by PiotrNestor** [getgauge/gauge-python#130]
### Description
Using pudb full-screen terminal debugger always gives only rows=24,columns=80 even if the terminal has different size

Running pudb with a Python file directly gives the correct terminal size
 
### Steps to reproduce
1. Add to step_impl.py:     from pudb import set_trace; set_trace()
2. gauge run specs/example.spec
3. The pudb screen is shown as rows=24,columns=80

### Information that will help us debug

* Gauge version 1.0.3
* Gauge Python plugin version 0.3.4
* Python version 3.6.7
* `getgauge` package version, run `pip3 show getgauge` to get it
Name: getgauge
Version: 0.3.4
Summary: Enables Python support for Gauge
Home-page: https://github.com/getgauge/gauge-python
Author: Gauge Team
Author-email: getgauge@outlook.com
* OS information: Ubuntu as Linux subsystem in Windows 10

**Comment by sriv** [comment]
I am guessing 80x24 is the default [`term_size`](https://github.com/inducer/pudb/blob/master/pudb/debugger.py#L518) in pudb. You can try setting `term_size` in the call to `set_trace`.

**Comment by PiotrNestor** [comment]
Pudb window size should use the full terminal window size. When you run Pudb with pure Python that's what happens.

Try the Gauge Python example project in a terminal window with bigger size than 80x24:
```
python step_impl/step_impl.py
```
where you have the following Python code at the top of the Python module.
```
from pudb import set_trace; set_trace()
import shutil
print(shutil.get_terminal_size())
```

Then try the same with:
```
gauge run specs/example.spec
```

**Comment by NivedhaSenthil** [comment]
Hope the suggestions above helped. Feel free to open new issue if you face any problem with gauge and gauge-python.
