### ISSUE TITLE
Can't start specification from command line 

### ISSUE THREAD

**Issue by akalaiselvan** [getgauge/gauge-python#138]
### Description
I have a complete regression automation environment in Gauge framework which i have been running from ide which is working fine . Now the problem is when i tried to run the test from command it is throwing an error message like "Step implementation not found => step name "

### Steps to reproduce
1.Test which is running smooth in ide
2. Tried to run via cmd

### Information that will help us debug

* Gauge version 1.0.3
* OS information windows 7

**Comment by nehashri** [comment]
@akalaiselvan Can you run `gauge -v` in cmd and paste its contents here?
Which ide are you using to run?

**Comment by akalaiselvan** [comment]
Gauge version : 1.0.3
Commit Hash: ff6c0c3

Plugins
-------

html-report <4.0.6>
java <0.6.9>
screenshot <0.0.1>

**Comment by nehashri** [comment]
@akalaiselvan You have raised this issue in Gauge python, but you do not have the Gauge python plugin installed. I see that you have the java plugin installed, is your project a java or python project?

Also, I see that your versions of Gauge and java are not the latest. Have your tried updating your versions?

If your project is a Java project, have you used any dependency management tools like Gradle or Maven? If so, what are their versions and  what are the versions of the gauge plugins for maven or gradle?
