### ISSUE TITLE
AttributeError: 'PythonNode' object has no attribute 'value'

### ISSUE THREAD

**Issue by max90727** [getgauge/gauge-python#140]
### Description
Expect behavior, gauge server runs after the command  'gauge run <spec>'

### Steps to reproduce
1. run command 'gauge run <spec>'
2. 
### Information that will help us debug

* Gauge version
Gauge version: 1.0.5
Commit Hash: 562f036

Plugins
-------
html-report (4.0.8)
python (0.3.5)
screenshot (0.0.1)

* Python version
Python 3.6.8

* `getgauge` package version, run `pip3 show getgauge` to get it
Version: 0.3.5
Summary: Enables Python support for Gauge
Home-page: https://github.com/getgauge/gauge-python
Author: Gauge Team

* OS information
Win10

Error Msg:
File "start.py", line 67, in <module>
    main()
  File "start.py", line 26, in main
    load_implementations()
  File "start.py", line 35, in load_implementations
    load_files(d)
  File "Python\Python36\site-packages\getgauge\static_loader.py", line 26, in load_files
    load_steps(pf)
  File "Python\Python36\site-packages\getgauge\static_loader.py", line 7, in load_steps
    for funcStep in python_file.iter_steps():
  File "Python\Python36\site-packages\getgauge\parser_parso.py", line 81, in iter_steps
    for func, decorator in self._iter_step_func_decorators():
  File "Python\Python36\site-packages\getgauge\parser_parso.py", line 55, in _iter_step_func_decorators
    if decorator.children[1].value == 'step':
AttributeError: 'PythonNode' object has no attribute 'value'

**Comment by shubhamsc** [comment]
@max90727 Can you give more details about how are you getting this error. Are you created any project or worked with sample project. 

Provide complete steps which you follow before running the gauge test. That will helpful to replicate the issue. How did you -
1.  Install gauge and plugin?
2. Create the project?
3. Running gauge (from: Command line or IDE)?

**Comment by max90727** [comment]
1. Install gauge and plugin?
choco install gauge (installed 1.0.3)
choco update gauge (update to 1.0.4)
gauge install python

2. Create the project?
gauge init python

3. Running gauge 
gauge run specs (command line)

In my specs implement, one of the imported files has `@value.setter`. 
I noticed that error did not show up after I removed the setter. However, I need the setter for the value. To be more clear here is the directory looks like.

specs/
step_impl/
                step_impl.py
                 library.py (`@value.setter` is here)

**Comment by max90727** [comment]
Sorry. I clicked the wrong button. Not closed

**Comment by BugDiver** [comment]
@max90727  Thanks for reporting the issue. I am able to replicate it at my end. We will be fixing this issue soon.

### Steps to replicate
* gauge init python
* Add following impl inside a file (in the impl dir)
```py
class Foo:

    def __init__(self,x):
        self.x = x

    @property
    def x(self):
        return self.__x

    @x.setter
    def x(self, x):
       self.__x = x
```
* gauge run specs

### Dev Notes

The issue is happening because the static parser is trying to read all the decorators while parsing the file.

**Comment by shubhamsc** [comment]
The fix should be available in nightly >= 28-05-2019

**Comment by max90727** [comment]
The latest nightly build solved the issue. 
Thank you.
