### ISSUE TITLE
Gauge Don‘t support UTF-8

### ISSUE THREAD

**Issue by 591361884** [getgauge/gauge-python#144]
### Description
Gauge do not support utf-8. 

### Steps to reproduce
1.
2.
3.

### Information that will help us debug

* Gauge version 1.0.4
* Gauge Python plugin version 0.3.5
* Python version 3.5.2
* `getgauge` package version, run `pip3 show getgauge` to get it
* OS information

The Solution way: 
parser_parso.py line29 change from `with open(file_path) as f:` to ` with open(file_path,encoding='utf-8') as f:`

**Comment by negiDharmendra** [comment]
@591361884 Please share a sample project. Please feel free to extend your valuable contribution through a PR with the change you have suggested.

**Comment by BugDiver** [comment]
@591361884 Can you please verify this issue?
Are you facing this issue with a particular text/symbol in your python file?
As @negiDharmendra requested a sample project would be really helpful for us to replicate the issue.

**Comment by SPmaster** [comment]
`open(file_path,encoding='utf-8')`  works for me on win 10 (10.0.18362)

[gauge-test.zip](https://github.com/getgauge/gauge-python/files/3779807/gauge-test.zip)
Thanks!
