### ISSUE TITLE
Structure log messages

### ISSUE THREAD

**Issue by nehashri** [getgauge/gauge-python#150]
Gauge can now understand plugin's log messages when it is structured properly (refer getgauge/gauge#216) for changes made in Gauge. The runner must now start logging in this format so that Gauge understands the messages properly.

**Comment by Debashis9012** [comment]
This has been verified and found fixed.
Tested version: ```0.3.6.nightly-2019-07-04```

**Comment by Debashis9012** [comment]
At first run gauge run specs runners related information are not available
in gauge.log. Runners logs are appearing only after second run.

Gauge version: 1.0.6.nightly-2019-07-16
Commit Hash: 75d9328

Plugins
-------
dotnet (0.1.2.nightly-2019-07-15)
python (0.3.6.nightly-2019-07-16)
ruby (0.5.3.nightly-2019-07-15)

**Comment by Debashis9012** [comment]
Runners related logs added properly to gaulge.log file.
This has been verified and found fixed the below version.
```
Gauge version: 1.0.6.nightly-2019-07-19
Commit Hash: c215a9f

Plugins
-------
csharp (0.10.6.nightly-2019-07-22)
dotnet (0.1.2.nightly-2019-07-22)
html-report (4.0.9.nightly-2019-07-22)
java (0.7.3.nightly-2019-07-22)
python (0.3.6.nightly-2019-07-22)
ruby (0.5.3.nightly-2019-07-22)
screenshot (0.0.1)
xml-report (0.2.2.nightly-2019-07-22)
```
