### ISSUE TITLE
Validation error with UTF-8 [Python 2.7]

### ISSUE THREAD

**Issue by vquemener** [getgauge/gauge-python#157]
### Description
Hi there,

I am experiencing validation issues when I use UTF-8 characters in the name of my steps.

### Steps to reproduce

1. Setup a new project:
```bash
$ gauge init python
```
2. Create some basic specs with UTF-8 characters:
```bash
$ cat >specs/example.spec <<EOF
# Specification Heading

## Scenario heading

* Step using the character é
EOF
```
3. Implement the associated step:
```bash
$ cat >step_impl/step_impl.py <<EOF
# -*- coding: utf-8 -*-
from getgauge.python import step

@step("Step using the character é")
def step_func():
    assert True
EOF
```

4. Try to validate the specs:
```bash
$ gauge validate specs
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
[ValidationError] /home/user/workspace/gauge/specs/example.spec:5 Invalid response from runner for Validation request => 'Step using the character é'
```

5. Note that the problem is specific to Python 2.X:
```bash
$ sed -i 's/^GAUGE_PYTHON_COMMAND.*/GAUGE_PYTHON_COMMAND = python3/' env/default/python.properties
$ gauge validate specs
No errors found.
```

### Information that will help us debug

* Gauge version: 1.0.6
* Gauge Python plugin version: 0.3.5
* Python version: 2.7.16
* `getgauge` package version: 0.3.5
* OS information: Fedora 30

**Comment by Apoorva-GA** [comment]
@vquemener I can see the issue in python 2.7.10 where as like you have already mentioned its specific to Python 2.X and works fine with Python3.

So it would be better if you could upgrade to Python3 as Python2 will not be maintained starting from Jan 2020. 

Also feel free to raise a Pull request with the fix.

**Comment by vquemener** [comment]
Unfortunately, for now I'm stuck with Python 2.7 due to a dependency on a third-party proprietary library. I guess I will have to remove the accents from the name of my steps, and later on I will see if I can take some time to work on a fix and a PR.

In the meantime, feel free to close this issue. And thank you for your time.

**Comment by jeremieflrnt** [comment]
Hi,
I have the same issue:
ValidationError/Step implementation not found for every step with é, à, etc.
But i'm using Python 3 :
* Gauge version: 1.1.1 Commit Hash: 6e0d83f
* Gauge Python plugin version (0.3.9)
* Python version 3.8.3
* Windows 10 (OK with Linux)

Would you please have a look?

**Comment by zabil** [comment]
I think this is fixed via https://github.com/getgauge/gauge-python/compare/v0.3.9...master

A release needs to happen

**Comment by sriv** [comment]
gauge-python 0.3.10 has been released and should include this fix. 

Closing this.
