### ISSUE TITLE
getting error while installing python from source

### ISSUE THREAD

**Issue by Debashis9012** [getgauge/gauge-python#167]
### Excepted Result:
Python plugin should be successfully installed without any error

### Actual Result:
Getting below error while installing python plugin from source:
```
.{"logLevel": "error", "message": "Failed to parse foo.py:3 '\"'"}
....{"logLevel": "error", "message": "Decorator step accepts either a string or a list of strings - 1:foo.py"}
.{"logLevel": "error", "message": "Decorator step accepts either a string or a list of strings - 3:foo.py"}
.{"logLevel": "error", "message": "Decorator step accepts either a string or a list of strings - 1:foo.py"}
.........................{"logLevel": "error", "message": "Failed to parse foo.py: Untreated elements: ''"}
.{"logLevel": "error", "message": "Decorator step accepts either a string or a list of                 strings - %s"}
.{"logLevel": "error", "message": "Decorator step accepts either a string or a list of                 strings - %s"}
.{"logLevel": "error", "message": "Decorator step accepts either a string or a list of                 strings - %s"}
```

### Steps to reproduce
1. clone python-repo
2. Installing package dependencies
   `pip install -r requirements.txt`
3. Installing
    `python build.py --install`

Tested version:
`7951536`

**Comment by Apoorva-GA** [comment]
@Debashis9012 This looks like a permission issue.
Could you please run `pip install -r requirements.txt --user` and then install it using `python build.py --install`.

**Comment by Debashis9012** [comment]
@Apoorva-GA  have tested as per your comments. I am able to install it successfully but getting error log as I have mentioned earlier.

**Comment by Apoorva-GA** [comment]
The logs are from valid tests which expects a failure. So its ok to have these logs.
