### ISSUE TITLE
Gauge Screenshots Fail

### ISSUE THREAD

**Issue by brywiser** [getgauge/gauge-python#17]
### Description
When I run tests in Gauge and they fail, I expect Gauge to take screenshots and put them into the fancy html report.  Currently they do not, we see "Failed to take screenshot using gauge screenshot"

### Steps to reproduce
1. Given you have tests written using Gauge
2. When you execute those tests
3. And one or more fail
4. Then you see the error message about failed screenshots

### Information that will help us debug

* Gauge: 0.9.4
* Gauge Python plugin version: 0.2.2
* Python version: 2.7.14
* `getgauge` : 0.2.2
* OS information: OS X El Capitan 10.11.6

**Comment by brywiser** [comment]
@kashishm is this issue resolved with the new version of Gauge?  Or is this still waiting to be prioritized?  Right now we have the workaround of adding "~/.gauge/plugins/screenshot/0.0.1/:/usr/local/bin:${PATH}" to PATH

**Comment by kashishm** [comment]
@brywiser It is working for me with the latest version of Gauge(0.9.6) and Gauge Python(0.2.3).

**Comment by BugDiver** [comment]
Closing this issue. Please feel free to reopen if the issue still exists.

**Comment by brywiser** [comment]
Im Sorry!!! I forgot to comment on this.  Yes it is working now!!!  Thank you all!
