### ISSUE TITLE
The link to Setup Guide on readme doesn't exist

### ISSUE THREAD

**Issue by ki4070ma** [getgauge/gauge-python#176]
### Description
The link to Setup Guide on readme doesn't exist.

### Steps to reproduce
https://github.com/getgauge/gauge-python/blob/master/README.md
 - Useful links > Setup Guide

Direct link
https://gauge-python.readthedocs.io/en/latest/contributing.html#development-guide

### Information that will help us debug
-

**Comment by Debashis9012** [comment]
I have removed the setup guide link. We must write the setup guide in the readme itself.
