### ISSUE TITLE
Upgrade Issue

### ISSUE THREAD

**Issue by akanksha4lal** [getgauge/gauge-python#18]
### Description
Error in running gauge python suite after latest update. 

### Steps to reproduce
1. Update gauge and related plugins

### Steps Tried
Remove all and reinstall from scratch
update getgauge to latest 0.2.2/0.2.3 [both tried]
Same configuration on another machine with High Sierra works fine. 

### Error
Getting error while running the default project - 

gauge run  specs/
TEST: opening 'start'
Python: 2.7.10
[ValidationError] /Users/ets-qa-macmini/Documents/tesproj/specs/example.spec:12 Step implementation not found => 'Vowels in English language are "aeiou".'

api.log shows below 
> 19:36:41.518 Sending API response: messageType:UnsupportedApiMessageResponse messageId:42 unsupportedApiMessageResponse:<>
> 10:33:18.465 Api Request Received: messageType:GetStepValueResponse messageId:165 stepValueRequest:<stepText:"The word <word> has <number> vowels." >

### Information that will help us debug
* Gauge version: 0.9.6
Plugins
html-report (4.0.2)
java (0.6.5)
python (0.2.3)
screenshot (0.0.1)
xml-report (0.2.0)
* Python version 2.7
* `getgauge` package version, run `pip show getgauge` to get it
Name: getgauge
Version: 0.2.0
Summary: Enables Python support for Gauge
Home-page: https://github.com/kashishm/gauge-python
Author: Kashish Munjal
Author-email: kashishmunjal64@gmail.com
License: MIT
Location: /usr/local/lib/python2.7/site-packages
Requires: protobuf, redBaron, colorama
* OS information - Mac OS Sierra 10.12.6

**Comment by kashishm** [comment]
> getgauge package version, run pip show getgauge to get it
> Name: getgauge
> Version: 0.2.0
> Summary: Enables Python support for Gauge

@akanksha4lal Did you update both Gauge Python and `getgauge` package? I see you have the latest version of Gauge Python plugin but you still have the older version of `getgauge` package i.e 0.2.0 and the latest is 0.2.3. Please update the package and try.

**Comment by akanksha4lal** [comment]
@kashishm I already tried that. I was trying with lower version, since one of other m/c is working with that combination. 

I tried fresh installation on new machine. It works. Just to get this old server working, can you tell me if any other python package version cause this issue ?

**Comment by kashishm** [comment]
@akanksha4lal This usually happens when there is a version mismatch between `gauge` and `getgauge` package. But If you have the latest of everything then it should have worked.

Can you try running the template project using `gauge init python && gauge run specs` and share the log files generated in the template project, If it doesn't work.

**Comment by gemunulk** [comment]
@kashishm I'm facing the same issue on windows8. 

- Gauge version: 0.9.7
- python (0.2.3)

Also, PFA screenshot herewith.

![image](https://user-images.githubusercontent.com/677439/34974965-94265cfe-fab5-11e7-8d98-abcc6d47865f.png)

**Comment by faceboole** [comment]
@Facing the same issue with Gauge version: 0.9.7 and python (0.2.3). PFA screenshot and logs herewith
![image](https://user-images.githubusercontent.com/32151112/34974873-2c413cee-fab5-11e7-9cd8-76265295c5a4.png)
[api.log](https://github.com/kashishm/gauge-python/files/1633847/api.log)
[gauge.log](https://github.com/kashishm/gauge-python/files/1633848/gauge.log)

**Comment by gemunulk** [comment]
OK. In my case it was due to old getgauge version.  Uninstalling old getgauge and reinstalling resolved this for me.
Steps:
- pip uninstall getgauge
- pip install getgauge


![image](https://user-images.githubusercontent.com/677439/34975536-4564661c-fab8-11e7-85bb-1c6c1dc103d7.png)

**Comment by akanksha4lal** [comment]
I re installed Mac OS on that machine, since I was short on time. Its working now.
Will re open in case of issues.
