### ISSUE TITLE
[Feature Request] Update ptvsd to debugpy 

### ISSUE THREAD

**Issue by luabud** [getgauge/gauge-python#180]
Hi! 

I'm a PM working on https://github.com/Microsoft/vscode-python, and I recently learned about the Gauge extension and that it uses ptvsd to debug specifications (which is really cool btw 😊). 

I'm opening this issue because mid next month we'll update ptvsd to debugpy in the Python extension, and we're planning to support ptvsd only until May 1st. Since this could break debugging in the Gauge extension for Python users, I'm opening this request now as a heads up 😊.

Thanks!

**Comment by zabil** [comment]
Thanks for letting us know!
