### ISSUE TITLE
version 0.3.9 Timed out connecting to python

### ISSUE THREAD

**Issue by congqiu** [getgauge/gauge-python#192]
### Description

Error ----------------------------------

[Gauge]
Failed to start gauge API: Timed out connecting to python

ps: uninstall version 0.3.9 and gauge install python -v 0.3.8 is right.

### Information that will help us debug

* Gauge version: 1.0.8
* Gauge Python plugin version: 0.3.9
* Python version: 3.5.2
* `getgauge` package version: 0.3.8
* ubuntu:16.04 docker

**Comment by NivedhaSenthil** [comment]
`getgauge package version: 0.3.8` has to 0.3.9 for it to work fine... gauge-python should have taken care of installing the right version of pip package was there any other error during the run ? if possible please do share the log files...
meanwhile you can try installing the package manually `pip install getgauge`
