### ISSUE TITLE
grpcio update and language runner error

### ISSUE THREAD

**Issue by Flintols** [getgauge/gauge-python#199]
### Description
had Visual Studio Code running (1.48.2), it updated (1.49.0), 
now
receive warning : Current gauge language runner is not compatible with gauge LSP
receive error: unable to connect to runner : Timed out connecting to python
checked for updates, and found grpcio has new version 1.32.0, so ran update, but it says incompatible 
  with getgauge, needs 1.28.1
still working on finding solution for language runner error..
### Steps to reproduce
1. install grpcio with pip
2. receive error

### Information that will help us debug

gauge notifications:
--> notif: initialized: {}
<-- request #0: client/registerCapability: {"registrations":[{"id":"gauge-fileWatcher","method":"workspace/didChangeWatchedFiles","registerOptions":{"watchers":[{"globPattern":"c:/repository/pytester/**/*{.spec,.md,.cpt}","kind":5}]}}]}
--> request #1: gauge/getRunnerLanguage: null
<-- result #1: gauge/getRunnerLanguage: "python"
--> result #0: client/registerCapability: null

* Gauge version: 1.1.1
* Gauge Python plugin version: python (0.3.11)
* Python version : Python 3.7.6
* `getgauge` package version : Version: 0.3.11
* OS information : Windows 10
* VSCode version : 1.49.0

**Comment by BugDiver** [comment]
@Flintols I could not replicate the issue. It's working fine for me.
The steps which I tried
* Make sure `python` and `pip` is installed
* `gauge init python`
* `pip install --user -r requirements.txt`
* open the project in vs code (make sure `Gauge` and `mspython` plugin is installed)

**Comment by Flintols** [comment]
I am not sure its fixed, but installing the 64bit version of python has it working now, although still getting [Gauge]Failed to start gauge API: Timed out connecting to python
from time to time.

**Comment by Flintols** [comment]
and The Gauge server crashed 5 times in the last 3 minutes. The server will not be restarted.

**Comment by Flintols** [comment]
this is my pip list:
ansicon           1.89.0   
appdirs           1.4.4    
assertpy          1.1      
astroid           2.4.2    
baron             0.9      
bcrypt            3.2.0    
certifi           2020.6.20
cffi              1.14.2   
chardet           3.0.4    
colorama          0.4.3    
colorclass        2.2.0    
cpppo             4.1.0
cryptography      3.1
cycler            0.10.0
debugpy           1.0.0rc2
decorator         4.4.2
dictdiffer        0.8.1
docopt            0.6.2
future            0.18.2
getgauge          0.3.11
greenery          2.1
grpcio            1.28.1
idna              2.10
imageio           2.9.0
imutils           0.5.3
ipaddress         1.0.23
iso8601           0.1.12
isort             5.5.2
kiwisolver        1.2.0
lazy-object-proxy 1.4.3
matplotlib        3.3.1
mccabe            0.6.1
minimalmodbus     1.0.2
MplayerCtrl       0.3.3
networkx          2.5
numpy             1.19.2
nunit             0.0.3
opencv-python     4.4.0.42
paramiko          2.7.2
parso             0.8.0
Pillow            7.2.0
pip               20.2.3
pip-check         2.6
pip-upgrade       0.0.6
pip-upgrader      1.4.15
pluggy            0.13.1
protobuf          3.13.0
py2exe            0.9.2.2
pycparser         2.20
pylint            2.6.0
pymodbus          2.4.0
PyMsgBox          1.0.8
PyNaCl            1.4.0
pyparsing         2.4.7
pyserial          3.4
pysftp            0.2.9
python-dateutil   2.8.1
pythonnet         2.5.1
PyWavelets        1.1.1
pyxlsb            1.0.6
redbaron          0.9.2
requests          2.24.0
robotframework    3.1.2
rply              0.7.7
scikit-image      0.17.2
scipy             1.5.2
Send2Trash        1.5.0
setuptools        47.1.0
sftp-client       1.0.4
six               1.15.0
termcolor         1.1.0
terminaltables    3.1.0
tifffile          2020.9.3
toml              0.10.1
toolz             0.10.0
typed-ast         1.4.1
unit-conversion   1.0.2
urllib3           1.25.10
visa              1.0.0
wheel             0.35.1
wrapt             1.12.1
xlrd              1.2.0

**Comment by Flintols** [comment]
pip-check tells me:
![image](https://user-images.githubusercontent.com/48215917/93217116-32bc9f00-f72e-11ea-8979-3fab4474ccf3.png) so I tried to get up to date, but am limited with grpcio because of getgauge

**Comment by NivedhaSenthil** [comment]
seems like the version updates from dependabot is not being picked up for pip packages release as `setup.tmpl` is not updated
