### ISSUE TITLE
Exception while loading step implementations from file not logged

### ISSUE THREAD

**Issue by tobias-lehmann-aperto** [getgauge/gauge-python#228]
https://github.com/getgauge/gauge-python/blob/c4b87a84f9e523ea09b432a0bb354bdd33da5236/getgauge/impl_loader.py#L75

The log includes the affected class, but the exception itself is not formatted into the log message.

**Comment by sriv** [comment]
Good catch, and it has been a source of pain for a few folks already. Would you be interested in sending a PR with whatever additional information you think would be valuable here?

**Comment by tobias-lehmann-aperto** [comment]
Sure, I will see if I have a little time on my hand today or tomorrow.

________________________________
Von: Srikanth <notifications@github.com>
Gesendet: Montag, 1. März 2021 17:21:52
An: getgauge/gauge-python
Cc: Lehmann, Tobias; Author
Betreff: [External] Re: [getgauge/gauge-python] Exception while loading step implementations from file not logged (#228)


WARNING: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.


Good catch, and it has been a source of pain for a few folks already. Would you be interested in sending a PR with whatever additional information you think would be valuable here?
