### ISSUE TITLE
load_files method taking 40+ seconds

### ISSUE THREAD

**Issue by skorber** [getgauge/gauge-python#250]
The load step implemenations step is taking a long time in when we moved from python 3.7.9 to 3.9.9. About 30 extra seconds on this single method. We used getgauge 0.3.9 for Python 3.7.9 and now are using getgauge 0.3.17. We also moved from Gauge 1.0.7 n Python 3.7.9 to Gauge 1.4.2. All the step implementation files remain the same.

**Comment by molex-steve** [comment]
Seems that the parser method is taking the longer time: https://github.com/getgauge/gauge-python/blob/eee95574e447c4bd180699b8017abd5b13a4a126/getgauge/parser.py#L8

About 2 seconds per .py file in step_impl folder

**Comment by chadlwilson** [comment]
Closing as stale, please comment if this is still an issue in later pythons/gauge-pythons.
