### ISSUE TITLE
Getting error when I provide the table at the scenario & step level

### ISSUE THREAD

**Issue by balaji2711** [getgauge/gauge-python#258]
Getting error when I provide the table at the scenario & step level

**Gauge version: 1.4.3**
**IDE: VS code**

1. Create a spec file.
2. Provide the table at the scenario & step level
3. Observe the spec file.

Actual result: Getting the message as 'Dynamic parameter <password> could not be resolved' and Dynamic parameter <username> could not be resolved. PFA for the screen-shot
Expected result: It should not be thrown any error message.

**The same works fine when I provide the table at the feature level.**

![image](https://user-images.githubusercontent.com/15344129/175493740-6af1b2a9-0673-40fb-bf38-ed6cd3d4d3b3.png)

**Comment by sriv** [comment]
for table driven scenario see https://docs.gauge.org/writing-specifications.html?os=linux&language=javascript&ide=vscode

you need to set `allow_scenario_datatable=true` in your properties file or via environment vars. Steps can only take table as parameters.

**Comment by balaji2711** [comment]
Yes. Already I had gone through the gauge documentation and enabled that flag as well in the properties file. 
Thanks for sharing the information 👍 

PFA for the screenshot of a properties file
![image](https://user-images.githubusercontent.com/15344129/175502816-b36c285e-4329-4fe7-80c8-4b8a62d8b4a9.png)

**Comment by sriv** [comment]
can you share a sample project for us to investigate?

**Comment by balaji2711** [comment]
I reinstalled the gauge extension in VS code and the problem resolves. Thanks for your time.

One more issue, have observed in the generated gauge report - 
The total executed scenarios are 3 and passed are 3 but in the report, it passed count shows as 2 -

![image](https://user-images.githubusercontent.com/15344129/175510249-5cff98a2-2d6f-4af7-b9ef-3875b6010373.png)

Spec file for your reference -
# Login Specification
* When I navigated to Login Page

## Login to the demo application
tags: sanity
* When I login as "standard_user" using "secret_sauce"
* Then login should be successful

## Login to the demo application with examples
tags: sanity
 |username     |password    |
 |-------------|------------|
 |standard_user|secret_sauce|
 |performance_glitch_user|secret_sauce|

* When I login as <username> using <password>
* Then login should be successful

**Comment by sriv** [comment]
possibly because of https://github.com/getgauge/gauge/issues/1299

**Comment by balaji2711** [comment]
Ok, Thanks for the update.

**Comment by balaji2711** [comment]
Hi @sriv, I'm getting an error message when I provide the table at the **step level**. Already the below flag is enabled n default.properties file -

# Enable scenario datatable
allow_scenario_datatable = true

![image](https://user-images.githubusercontent.com/15344129/175920978-5e0c6d50-cf8f-4c25-ab5c-5f62712e1744.png)

**Comment by sriv** [comment]
Scenario is the question H2 header starting with `##`. Scenario datatable has to be under it. You seem to have placed it as a step parameter

**Comment by balaji2711** [comment]
Yes, I want to pass the table at the step level. Is that possible?
