### ISSUE TITLE
Should be able to work seamlessly with workspaces

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-python#26]
**Actual behavior**
IDE features stops working after a couple of projects are added to the workspaces

**Steps to replicate**
* Create a gauge-python project
* Add it to the workspace
* Reload the project
* Double click and Open an example.spec file from the project (so that the file remains open even after Goto definition)
* Goto definition on a step.
* Keep adding more projects. 
> Note: Currently I am able to work with 2 projects in workspace. For the third project, IDE features do not work as expected. This may be a performance issue. The number of projects to be added to replicate the issue can differ.

**Version**
```
Gauge version: 0.9.8
Commit Hash: 8166611

Plugins
-------
python (0.2.4.nightly-2018-02-11)
```

**Comment by BugDiver** [comment]
@sguptatw  Is this issue still valid?
