### ISSUE TITLE
plugin 0.3.17 can not support Chinese

### ISSUE THREAD

**Issue by yicaifeitian** [getgauge/gauge-python#260]
**Describe the bug**

**To Reproduce**
Steps (or project) to reproduce the behavior:
1. Initialise a gauge project
2. Use the following piece of code
3. Run the gauge command
5. See error

```
$ gauge init python
$ gauge run specs
```
![image](https://user-images.githubusercontent.com/18083559/176642130-aaee3ab2-6fdb-4fae-82eb-972d5f3fbabb.png)

**Logs**

```
Paste any log or error messages here
```

**Expected behavior**

**Screenshots**

**Versions:**
 - OS [e.g. 10.15.6 (19G2021) please be specific ]
 - Python version 

```
gauge -v
```
![image](https://user-images.githubusercontent.com/18083559/176643188-ab614bc3-0fb0-455c-90ca-fa6697b54a50.png)

**Additional context**
windows 10

**Comment by haroon-sheikh** [comment]
@yicaifeitian This should now be available to test in v0.4.0. Let us know if that fixes the problem for you.
