### ISSUE TITLE
Rename module and package

### ISSUE THREAD

**Issue by zabil** [getgauge/gauge-python#27]
### Description
Change the package name and structure so that it's

```
from gauge import step, before_scenario, Messages
````
Maintain backward compatibility by adding deprecations in the old style i.e 

```
from getgauge.python import step, before_scenario, Messages
```

**Comment by BugDiver** [comment]
I'm afraid it can't be done because a package named `gauge` already exists in `PyPI`.
Ref:  https://pypi.python.org/pypi/gauge
