### ISSUE TITLE
On successful refactor, files should get refreshed

### ISSUE THREAD

**Issue by BugDiver** [getgauge/gauge-python#30]
_From @sguptatw on February 12, 2018 10:43_

**Actual behavior**
Refactoring is successful, but the specification file starts showing parse errors for the refactored step.

**Steps to replicate**
* Create a `gauge-python` project
* In the IDE, refactor `The word "gauge" has "3" vowels.` to `The word "gauge" has "3" vowels something`
* The refactored step shows in the spec file as an unimplemented step
> Note: The implementation file and specification file have changed. The refactoring is successful. But the newly refactored step is shown as undefined.

**Version**
```
Gauge version: 0.9.8.nightly-2018-02-02
Commit Hash: bff4f46

Plugins
-------
python (0.2.4.nightly-2018-02-11)
```

Bug on story - https://github.com/getgauge/gauge-vscode/issues/81

_Copied from original issue: getgauge/gauge-vscode#137_

**Comment by BugDiver** [comment]
Fix should be available in gauge-python nightly  >= 16-02-2018

**Comment by sguptatw** [comment]
Blocked by https://github.com/getgauge/gauge/issues/943
