### ISSUE TITLE
After refactoring, find-usage statistics and step implementation recognition should work

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-python#31]
**Actual behavior**
The parameter name in the generated annotation after refactoring takes the value given in the text as the parameter name. 
`Find usages do not work` and `step implementation is not recognized`

**Steps to replicate**
* In a `gauge-python` project
* Refactor `Vowels in English language are "aeiou"` to `Vowels in English language are "aeiou" something else "" and "ddd"`

**Version**
```
auge version: 0.9.8.nightly-2018-02-15
Commit Hash: dfbaee0

Plugins
-------
python (0.2.4.nightly-2018-02-16)
```
pip version
```
Name: getgauge
Version: 0.2.4.dev20180216
Summary: Enables Python support for Gauge
Home-page: https://github.com/getgauge/gauge-python
Author: Gauge Team
Author-email: getgauge@outlook.com
License: MIT
Location: /Library/Python/2.7/site-packages
Requires: protobuf, redBaron
```
Bug on story - https://github.com/getgauge/gauge-vscode/issues/81

**Comment by BugDiver** [comment]
@sguptatw In the given steps you have mentioned to use `gauge-js` project. Shouldn't this issue be in `gauge-js` instead of `gauge-python`?

**Comment by sguptatw** [comment]
@BugDiver : The steps to replicate is updated to use `gauge-python` project.

**Comment by BugDiver** [comment]
Should be available in nightly >= 07-02-2018

**Comment by sguptatw** [comment]
Find usages statistics does not reflect the correct details

**Comment by sguptatw** [comment]
The usage statistics are displayed correctly. However, in code there is a repeat in the parameter name generated in the signature. This does not allow the user to refactor the step again
Getting the error - `Refactoring failed due to parse errors`

The name generated for the parameter with empty value should not be based on existing parameter names

**Comment by sguptatw** [comment]
The usage statistics is correct when the step impl is
```
@step("Show subtitle <Choose your OS & download>")
def show_subtitle(arg1):
    assert False, "Add implementation code"
```

However on refactoring to `* Show subtitle "Choose your OS & download" "whatever !@#$%^&*()~"`. The usage displayed is wrong
```
@step("Show subtitle <Choose your OS & download> <whatever !@#$%^&*()~>")
def show_subtitle(arg1, arg1):
    assert False, "Add implementation code"
```

**Comment by BugDiver** [comment]
The fix should be available in nightly >= 23-05-2018
