### ISSUE TITLE
Goto definition of another step after generate stub gives error

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-python#32]
**Expected behavior**
Should not get `use of closed network connection`

**Actual behavior**
Getting the error

**Steps to replicate**
* Create a `gauge init python`
* add an unimplemented step
* `Generate stub` for this step - copy the implementation
* Now try goto definition of step `* The word "gauge" has "3" vowels.`
> Note: We get the error - `use of closed network connection
  Code: 0 `

**Version**
```
Gauge version: 0.9.8.nightly-2018-02-15
Commit Hash: dfbaee0

Plugins
-------
python (0.2.4.nightly-2018-02-16)
```
Bug on story https://github.com/getgauge/gauge-python/issues/19

**Comment by BugDiver** [comment]
Not able to reproduce with latest `gauge` and `gauge-python`.
