### ISSUE TITLE
Warning log: ModuleNotFoundError: No module named 'pkg_resources'

### ISSUE THREAD

**Issue by ZurdenRo** [getgauge/gauge-python#344]
**Describe the bug**
every time when I click  `run scenario` in spec file: the test case run Successfully but appear this log: ModuleNotFoundError: No module named 'pkg_resources', 

**To Reproduce**
Steps (or project) to reproduce the behavior:
1. Initialise a gauge project
2. click  `run scenario` in spec file
4. Log:
```CMD
import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'
```
**Expected behavior**
Doesn't appear the warning log.

**Versions:**
Python: 3.11.5
OS: Window 10
Gauge version: 1.6.6
Commit Hash: 209816e

Plugins
-------
html-report (4.3.1)
python (0.4.3)
screenshot (0.2.0)

**Comment by chadlwilson** [comment]
Please stop opening new issues in various places for the same thing. There is nothing additional here from what you put in #343 

Create 1 discussion or issue in 1 place for 1 problem.
