### ISSUE TITLE
Getting error when Debug option is used consecutively

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-python#36]
**Expected behavior**
Should be able to debug without getting an error

**Actual behavior**
Getting the following errors
<img width="672" alt="debuggerterminatedunexpectedly" src="https://user-images.githubusercontent.com/6310197/36828149-fc64650e-1d3d-11e8-9850-30b173898784.png">
<img width="673" alt="debuggerconnectionrefused" src="https://user-images.githubusercontent.com/6310197/36828152-009cfaaa-1d3e-11e8-8a96-6ce61ccc6610.png">

**Steps to replicate**
* On a `gauge-python` project. 
* Apply breakpoint. 
* Start debugging. once the debugging is complete. Restart the debugging process.
> The above error was observed on Windows.

**Version**
```
Gauge version: 0.9.8.nightly-2018-02-28
Commit Hash: d997b9a

Plugins
-------
python (0.2.4.nightly-2018-02-28)
```
Bug on story https://github.com/getgauge/gauge-python/issues/33

**Comment by riju91** [comment]
should be available in nightly >= 2018-04-04
