### ISSUE TITLE
Update use of pkg_resources in check_and_install_getgauge.py

### ISSUE THREAD

**Issue by eiri** [getgauge/gauge-python#373]
**Is your feature request related to a problem? Please describe.**

It seems that the use of `pkg_resources` is currently deprecated and `check_and_install_getgauge.py` is now raising a warning that looks like this ".../plugins/python/0.4.5/check_and_install_getgauge.py:5: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html"

There have been a breaking release of `setuptools` today that [affected plenty of projects](https://github.com/pypa/setuptools/issues/4519). It was hot-fixed later, but my concern is that some future release will also break `gauge-python`.  

**Describe the solution you'd like**

I believe it would be helpful to pro-actively update `check_and_install_getgauge.py` not to use deprecated `pkg_resources`.

**Comment by chadlwilson** [comment]
Are you willing to submit a PR?

**Comment by eiri** [comment]
Sure, will be glad to.

**Comment by eiri** [comment]
@chadlwilson thank you for accepting my PR and for the quick turnaround!

**Comment by chadlwilson** [comment]
No worries, thanks for the help. Goodness knows, we need it!
