### ISSUE TITLE
Add a webdriver template to gauge-python

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-python#38]
**Actual behavior**
Only the basic template is available

**Proposed behavior**
- Have a template `python-selenium` for initializing a project with webdriver.

**Version**
```
Gauge version: 0.9.8.nightly-2018-03-05
Commit Hash: 63aeb3b

Plugins
-------
python (0.2.4.nightly-2018-02-28)
```

**Comment by zabil** [comment]
Added
