### ISSUE TITLE
Remove the property PYTHONUNBUFFERED

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-python#39]
**Expected behavior**
Remove the unused property

**Actual behavior**
In a newly created python project, python.properties has a property `PYTHONUNBUFFERED`. This is an unused property

**Steps to replicate**
* Create a python project
* Open the python.properties in the env/default folder

**Version**
```
Gauge version: 0.9.8.nightly-2018-03-06
Commit Hash: 4f23723

Plugins
-------
python (0.2.4.nightly-2018-03-06)
```

**Comment by BugDiver** [comment]
Fix should be available in nightly >= 07-03-2018
