### ISSUE TITLE
Runner should log to log files when started gauge is started as daemon

### ISSUE THREAD

**Issue by nehashri** [getgauge/gauge-python#40]
Runner console logs should be logged to the log file when started as daemon.
When gauge is running as lsp server, runner console should be redirected to lsp.log.
When gauge is running as api daemon, runner console should be redirected to api.log.
In the above two cases, runner should log to the log files with proper formatting. Current log file format for gauge is 'HH:MM:ss.l'. (eg :- 12:50:11.221)

When gauge is started in CLI, console should be the standard output. It should not log with timestamp.

**Comment by nehashri** [comment]
should be available in gauge nightly >= 7-03-2018, gauge-python >= 8-03-2018

**Comment by sguptatw** [comment]
The PR has been reviewed
