### ISSUE TITLE
Example fails with python 3.6.4

### ISSUE THREAD

**Issue by jackperalta** [getgauge/gauge-python#44]
### Description
I have Windows 10 and Python 3.6.4 installed.

When I run the **gauge init python** example the following error occurs

```
Traceback (most recent call last):
  File "start.py", line 4, in <module>
    from colorama import Style, init
ModuleNotFoundError: No module named 'colorama'
Failed to start gauge API: Runner with pid 6576 quit unexpectedly(exit status 1).
```
I would assume with a fresh gauge python project, running the example would simply work

### Steps to reproduce
1. Install Python 3.6.4
2. Create example project `gauge init python`
3. Call `gauge run`

### Information that will help us debug
```
Gauge version: 0.9.7
Commit Hash: bc9784c

Plugins
-------
gauge-jira (0.0.1)
html-report (4.0.3)
java (0.6.6)
js (2.1.0)
report-seed (0.0.1)
screenshot (0.0.1)
spectacle (0.1.2)
xml-report (0.2.0)
```
* python 3.6.4

**Comment by BugDiver** [comment]
@jackperalta you need to install the `gauge-python` to run a gauge-python project.

Read the [docs](http://gauge-python.readthedocs.io) to get started with gauge and python.
