### ISSUE TITLE
Unable to install pip gauge for nightly

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-python#45]
**Expected behavior**
If python nightly is python (0.2.5.nightly-2018-03-20), then the user should be able to install
`pip install --pre getgauge==0.2.5.dev.20180320`

**Actual behavior**
Getting the error
```
  Could not find a version that satisfies the requirement getgauge==0.2.5.dev.20180320 (from versions: 0.0.1, 0.0.2, 0.0.3, 0.0.4, 0.1.0, 0.1.1, 0.1.2, 0.1.3, 0.1.4, 0.1.5, 0.1.6, 0.1.7, 0.2.0, 0.2.1, 0.2.2, 0.2.3, 0.2.4.dev20180207, 0.2.4.dev20180208, 0.2.4.dev20180209, 0.2.4.dev20180211, 0.2.4.dev20180215, 0.2.4.dev20180216, 0.2.4.dev20180220, 0.2.4.dev20180223, 0.2.4.dev20180227, 0.2.4.dev20180228, 0.2.4.dev20180302, 0.2.4.dev20180306, 0.2.4.dev20180307, 0.2.4.dev20180308, 0.2.4.dev20180312, 0.2.4.dev20180316, 0.2.5.dev20180319, 0.2.5)
No matching distribution found for getgauge==0.2.5.dev.20180320
```
**Steps to replicate**
* install python nightly-0.2.5 2018/03/20
* `pip install --pre getgauge==0.2.5.dev.20180320`
> Getting the above error

**Comment by BugDiver** [comment]
The nightly pipeline configuration has been updated. The nightly packages are created just before publishing it. 
The error should be fixed.
