### ISSUE TITLE
Should not list _init_.py in the file list to generate step implementation

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-python#49]
**Expected behavior**
The __init__.py files are required to make Python treat the directories as containing packages; This should not be listed for where to generate the step implementation.

**Actual behavior**
The _init_.py is being listed in the file list suggestions

**Steps to replicate**
* Open VSCode
* Add an unimplemented step
* Ctrl+. on the step
* Choose `Create step implementation`
> In the list of files that come up, _init_.py is shown. This should not be in the list

**Version**
```
Gauge version: 0.9.8

Plugins
-------
csharp (0.10.2.nightly-2018-03-27)
email-report (0.0.1)
html-report (4.0.4.nightly-2018-03-28)
java (0.6.7.nightly-2018-03-16)
js (2.2.0.nightly-2018-03-29)
python (0.2.5)
report-seed (0.0.1)
ruby (0.4.3.nightly-2018-03-16)
screenshot (0.0.1)
xml-report (0.2.1.nightly-2018-03-28)
```
pip show getgauge
```
Name: getgauge
Version: 0.2.5
Summary: Enables Python support for Gauge
Home-page: https://github.com/getgauge/gauge-python
Author: Gauge Team
Author-email: getgauge@outlook.com
License: MIT
Location: c:\python36\lib\site-packages
Requires: protobuf, redBaron, ptvsd
You are using pip version 9.0.2, however version 9.0.3 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
```

**Comment by riju91** [comment]
should be available in nightly >= 2018-04-30
