### ISSUE TITLE
Python process is not killed after shutdown/exit call

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-python#51]
**Expected behavior**
When a shutdown/exit call is made by the client, the Python orphan process should be killed

**Actual behavior**
The Python orphan process is not killed

**Steps to replicate**
* Run [LSP tests](github.com/getgauge/gauge-lsp-tests) using --env=python-wd
* On OSx top -u -s5 
> There are orphan Python processes.

**Version**
```
Gauge version: 0.9.8
Commit Hash: 61d692c

Plugins
-------
python (0.3.0.nightly-2018-04-13)
```

**Comment by BugDiver** [comment]
Should be fixed in nightly >= 18-04-2018

**Comment by sguptatw** [comment]
Fixed on OSx, Windows still an issue

**Comment by sguptatw** [comment]
Working as expected on
```
Gauge version: 0.9.8.nightly-2018-04-19
Commit Hash: 58298e2

Plugins
-------
python (0.3.0.nightly-2018-04-18)
```
