### ISSUE TITLE
IDE features should work as expected

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-python#52]
**Actual behavior**
The IDE features are not working as expected
- Find usage statistics are not displayed
- All steps in specification are marked as unimplemented

**Steps to replicate**
* Open a gauge-python project
> IDE features are not available

**Version**
```
Gauge version: 0.9.8
Commit Hash: 61d692c

Plugins
-------
python (0.3.0.nightly-2018-04-13)
```
**Pip Version**
```
Name: getgauge
Version: 0.3.0.dev20180413
Summary: Enables Python support for Gauge
Home-page: https://github.com/getgauge/gauge-python
Author: Gauge Team
Author-email: getgauge@outlook.com
License: MIT
Location: /Users/sswaroop/Library/Python/2.7/lib/python/site-packages
Requires: protobuf, redBaron, ptvsd, grpcio
```

**Comment by Apoorva-GA** [comment]
Fix should be available in gauge nightly >= 18/04/18
