### ISSUE TITLE
Indicate a mismatch between gauge-python installation and pip show getgauge

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-python#53]
**Proposed behavior**
User should be indicated about the mismatch until it is fixed

**Current behavior**
The user can see the mismatch by comparing 
`gauge version` and `pip show getgauge`

**Comment by sguptatw** [comment]
The version mismatch is not getting indicated even when `gauge run specs` is executed on a python project

**Version**
```
Gauge version: 0.9.8
Commit Hash: c23df9f

Plugins
-------
python (0.3.2.nightly-2018-05-03)

PS ...\python\python3> pip show getgauge
Name: getgauge
Version: 0.3.1
Summary: Enables Python support for Gauge
Home-page: https://github.com/getgauge/gauge-python
Author: Gauge Team
Author-email: getgauge@outlook.com
License: MIT
Location: c:\python27\lib\site-packages
Requires: redBaron, ptvsd, grpcio, futures
You are using pip version 9.0.3, however version 10.0.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
```

**Comment by Apoorva-GA** [comment]
Fix should be available in python nightly >= 4/5/18

**Comment by sguptatw** [comment]
The mismatch is shown when the command is executed from the command line. The following case should be handled

* Install latest gauge-python, older pip getgauge
* Open VSCode
* IDE Features do not appear
> After sometime the message given is `server crashed 5 times in 3 minutes`

The user should be able to see the message without opening the log file. The IDE should not crash.

**Comment by sguptatw** [comment]
**Expected behavior**
Should get a compatibility message even when pip getgauge is not installed.

**Actual behavior**
On `gauge run specs` getting the following error
```
Traceback (most recent call last):
  File "start.py", line 12, in <module>
    from getgauge import connection, processor
ImportError: No module named getgauge
Error ----------------------------------

Failed to start gauge API: Runner with pid 21004 quit unexpectedly(exit status 1).
```

**Comment by nehashri** [comment]
We can track the VS Code issue separately as it looks like it is a VS Code specific issue.

**Comment by NivedhaSenthil** [comment]
Fix should be available in nightly >= 15/05/2018

**Comment by sguptatw** [comment]
Instead of indicating the mismatch gauge now install corresponding getgauge module is installed

**Note**
While uninstalling python plugin, user will have to manually uninstall getgauge pip module.
