### ISSUE TITLE
CPU usage should be acceptable

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-python#54]
**Actual behavior**
The CPU usage on starting a `gauge-python` project is almost 100%

**Steps to replicate**
* Open a `gauge-python` project
> Note the CPU usage

**Comment by BugDiver** [comment]
Should be fixed in nightly >= 18-04-2018

**Comment by sguptatw** [comment]
Fixed on OSx, Windows still an issue

**Comment by sguptatw** [comment]
Working as expected on
```
Gauge version: 0.9.8.nightly-2018-04-19
Commit Hash: 58298e2

Plugins
-------
python (0.3.0.nightly-2018-04-18)
```

**Comment by marius-uncrop** [comment]
I'm able to replicate the issue using gauge version:
**$ gauge -v**
Gauge version: 0.9.9
Commit Hash: 8db625f
python (0.3.2)

**OS:**
$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"

**hardware specifications** : all attached
[hardware_specifications.txt](https://github.com/getgauge/gauge-python/files/2026621/hardware_specifications.txt)

After the gauge run command is run until the first test starts around 1 minute passes( during this time the processor usage is around 100% )
**htop screenshot:** 
![htop](https://user-images.githubusercontent.com/37572288/40362749-1b017f46-5dd6-11e8-9f31-5bd31990406d.png)

**gauge.log :**
14:34:32.871 Plugin python is already installed.
14:34:32.872 Plugin html-report is already installed.
14:34:32.872 Plugin spectacle is already installed.
**14:34:32.**872 Plugin flash is already installed.
**14:35:43**.994 # Check the item preview
**14:35:46**.811 ## Login with default credentials

**Notes to reproduce:**
The issue doesn't appear in the beginning of a new project, but after more step implementations are added. I cannot add the project i'm working on, but the issue can be reproduced starting with a new project

For example, using attached project(gauge-test.tar.gz) composed from the initial project template plus some dummy new step implementations the process needs more than 1 minute to start the tests while processor is at 100%
[gauge-test.tar.gz](https://github.com/getgauge/gauge-python/files/2026626/gauge-test.tar.gz)

**Comment by NivedhaSenthil** [comment]
Considerable optimisation for initialisation is done. Execution optimisation will be handled in #79

**Comment by sguptatw** [comment]
@marius-uncrop 
Thanks for reporting the issue.

This issue is about the performance issue during load. With the given project having loading also had an issue (project initialization). This has been addressed in the following version.

```
Gauge version: 0.9.9.nightly-2018-05-24
Commit Hash: 2150e31

Plugins
-------
python (0.3.3.nightly-2018-05-25)
```
> As mentioned by @NivedhaSenthil, the execution optimization will be done as a part of #79.

**Comment by marius-uncrop** [comment]
@sguptatw , @NivedhaSenthil ,
thanks for working on this; from the initial tests, I notice a huge improvement after this task + #79 .

your work is really appreciated !!!
