### ISSUE TITLE
A new user should be able to run specs after project initialization

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-python#58]
**Current behavior**
pip install getgauge is required

**Proposed behavior**
A user with only gauge installed should be able to work after initializing a project

**Steps to replicate**
* Ensure getgauge is not installed/uninstalled in pip
* Ensure python is not installed/uninstalled
* Create a new gauge-python project from VSCode.
* `gauge run specs` gives Failed to start gauge API
> gauge-python plugin is installed but getgauge is not installed on pip

**Version**
```
Gauge version: 0.9.8.nightly-2018-04-19
Commit Hash: 58298e2

Plugins
-------
html-report (4.0.4.nightly-2018-04-11)
python (0.3.0.nightly-2018-04-18)
```
Related to https://github.com/getgauge/gauge-vscode/issues/211

**Comment by NivedhaSenthil** [comment]
Fix should be available in nightly >= 17/05/2018
