### ISSUE TITLE
Debug adapter process has terminated unexpectedly

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-python#63]
**Expected behavior**
Should be able to debug seamlessly

**Actual behavior**
Debug adapter process has terminated unexpectedly

**Steps to replicate**
* Create a `gauge-python` project
* Debug Spec
* Debug Scenario
* Debug Spec
> The message appears `Debug adapter process has terminated unexpectedly`

**Version**
```
Gauge version: 0.9.8.nightly-2018-04-26
Commit Hash: 5bd699e

Plugins
-------
python (0.3.0.nightly-2018-04-26)
```

**Comment by sguptatw** [comment]
The Python process CPU usage is almost 100 in this scenario when Debugging is hung

**Comment by BugDiver** [comment]
@sguptatw  Can you tell what are you getting?

**Comment by BugDiver** [comment]
@sguptatw We can't fix debugger crash problem coz it's a problem with `vscode-python`.
The fix is about the high CPU usage. Please refer the above comment. It's a workaround which we have done.

**Comment by sguptatw** [comment]
@BugDiver The user should be able to stop debugging and proceed with other IDE actions. 
Clicking on stop debugging does not stop the gauge process/debugging process. Currently user has to restart the IDE to continue with other IDE actions.

**Comment by sguptatw** [comment]
This issue has been de-prioritized right now
