### ISSUE TITLE
Generate step implementation gives script error

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-python#65]
**Expected behavior**
Should be able to run spec after generating the step from spec

**Actual behavior**
`from getgauge. python import step` is added after the step definitions. So getting `TypeError: 'NoneType' object is not callable`

**Steps to replicate**
* Create a `gauge-python` project
* Add a new step in spec
* Generate step implementation
* Run the specs
> The type error is displayed

**Version**
```
Gauge version: 0.9.8.nightly-2018-04-26
Commit Hash: 5bd699e

Plugins
-------
python (0.3.0.nightly-2018-04-25)
```
Related to issue https://github.com/getgauge/gauge-vscode/issues/119

**Comment by nehashri** [comment]
fix should be available in nightly >= 30-4-18
