### ISSUE TITLE
Get error message in scenario hook

### ISSUE THREAD

**Issue by LvivEchoes** [getgauge/gauge-python#68]
### Description
For reporting test execution status to test case management systems - we should know, what actual happened with test, and pass this info to ticket/execution description.

### Steps to reproduce
1. Create any fail test
2. Create @after_scenario/@after_step hook
3. Go through context, and I can't find error message for fail.

### Information that will help us debug

* Gauge version 0.98
* Gauge Python plugin version 0.2.5
* Python version 3.6.5
* `getgauge` package version, run `pip3 show getgauge` to get it
* OS information OSX 10.13

**Comment by BugDiver** [comment]
Should be available in nightly >= 15-05-2018

**Comment by sguptatw** [comment]
The screenshot not being captured for hooks are captured as a separate issue
