### ISSUE TITLE
pip install dev version number is not consistent

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-python#71]
**Expected behavior**
`pip install --pre getgauge==0.3.2.dev.20180504 --user` should install a version of `Version: 0.3.2.dev.20180504`

**Actual behavior**
It is installing `Version: 0.3.2.dev20180504` and hence a version incompatibility error occurs and IDE features are not available

**Steps to replicate**
* Install python nightly `python (0.3.2.nightly-2018-05-04)`
* Install pip version `0.3.2.dev.20180504`
* Open VSCode IDE
> The IDE features are not available. Incompatibility message is seen in the logs.

**Version**
```
auge version: 0.9.8.nightly-2018-05-01
Commit Hash: 765d3e7

Plugins
-------
python (0.3.2.nightly-2018-05-04)
```

**Comment by BugDiver** [comment]
This is not an issue with `gauge` or `gauge-python`. Looks like this the behavior of `pip` which installs `X.X.X.dev.XXXXXXXX` as `X.X.X.devXXXXXXXX`.

The compatibility check needs to handle this.
