### ISSUE TITLE
With large number of steps the CPU usage is high when project is loaded

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-python#81]
**Expected behavior**
The CPU usage should be within an acceptable limit

**Actual behavior**
The CPU usage exceeds 90 and sometimes 100 as well

**Steps to replicate**
* Create a `gauge-python` project
* Create an implementation file with more than 100 steps
* Here is a sample project
[gauge-test.zip](https://github.com/getgauge/gauge-python/files/2030042/gauge-test.zip)
* Open it in VSCode

**Version**
```
Gauge version: 0.9.9.nightly-2018-05-21
Commit Hash: f7d0def

Plugins
-------
python (0.3.3.nightly-2018-05-21)
```

**Comment by NivedhaSenthil** [comment]
Same as #54. Should be fixed

**Comment by sguptatw** [comment]
On Linux the CPU usage is still above 95% when I open the implementation file. However, the time to load usage statistics has reduced drastically.

**Comment by sguptatw** [comment]
This increase is temporary, hence closing the issue
