### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-python#84]
_From @sguptatw on May 28, 2018 10:40_

**Expected behavior**
Should be able to execute specs seamlessly

**Actual behavior**
Getting
```
./start.sh: line 6: 53957 Segmentation fault      (core dumped) ${GAUGE_PYTHON_COMMAND} -u start.py $1
Error ----------------------------------

Failed to start gauge API: Runner with pid 53910 quit unexpectedly(exit status 139).

Get Support ----------------------------
        Docs:          https://docs.gauge.org
        Bugs:          https://github.com/getgauge/gauge/issues
        Chat:          https://gitter.im/getgauge/chat

Your Environment Information -----------
        linux, 0.9.9.nightly-2018-05-24, 2150e31
        html-report (4.0.5), java (0.6.8), js (2.3.1), python (0.3.3), ruby (0.5.1), screenshot (0.0.1), xml-report (0.2.1)
```
**Steps to replicate**
* Project - https://github.com/sguptatw/gauge-python-performance-usages.git
* Open VSCode
* On the VSCode terminal run `gauge run specs/specs1/example.spec`
* Open and close the spec file.
* Run again
> After a couple of runs getting this error

_Copied from original issue: getgauge/gauge#1064_

**Comment by NivedhaSenthil** [comment]
This is happening due to some failure in grpc. The issue in grpc can be tracked here https://github.com/grpc/grpc/issues/15581

**Comment by NivedhaSenthil** [comment]
doing a pip upgrade fixes this issue, as the default pip version when we do apt install is  9.0.1 that needed to be upgraded. This seems to happen because of an issue(https://github.com/pypa/setuptools/issues/951) in setuptools which is fixed in setuptools version > 36
