### ISSUE TITLE
grpc: the connection is unavailable

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-python#85]
**Expected behavior**
Should be able to continue working after executing the specs

**Actual behavior**
Getting the grpc: the connection is unavailable

**Steps to replicate**
* Project - https://github.com/sguptatw/gauge-python-performance-usages.git
* `gauge run` from VSCode terminal
> After a couple of runs opening the spec file example.spec gives the above error

Observed on linux

**Version**
```
Gauge version: 0.9.9.nightly-2018-05-24
Commit Hash: 2150e31

Plugins
-------
python (0.3.3.nightly-2018-05-28)
```

**Comment by NivedhaSenthil** [comment]
This happens due to killing of language run by segmentation fault  which is tracked in #84
