### ISSUE TITLE
Bad character in comment breaks Python parsing

### ISSUE THREAD

**Issue by BugDiver** [getgauge/gauge-python#86]
_From @opendragon on June 5, 2018 20:13_

### Expected behaviour
A simple step should execute.

### Actual behaviour
The Python plugin fails to parse code containing a comment with a special character in it.

### Steps to reproduce
1. Create the following specification file:
[001_short_test.spec.txt](https://github.com/getgauge/gauge/files/2073833/001_short_test.spec.txt)
2. Create the following Python file:
[Funcs.py.txt](https://github.com/getgauge/gauge/files/2073808/Funcs.py.txt)
Note the special character in the comment.
3. Run gauge against the specification file.

### Gauge version
Gauge version: 0.9.9
Commit Hash: 8db625f

Plugins
-------
go (0.1.2)
html-report (4.0.4)
java (0.6.7)
js (2.3.0)
json-report (0.2.2)
python (0.3.2)
ruby (0.5.0)
screenshot (0.0.1)
spectacle (0.1.2)
xml-report (0.2.0)

_Copied from original issue: getgauge/gauge#1074_

**Comment by BugDiver** [comment]
@opendragon  Can you please tell use error are you getting exactly? Also make sure you have `getgauge` pypi package installed (compatiable to version with gauge-python).

**Comment by opendragon** [comment]
Hi Vinay: 
Here is a text capture of the error, as well as the version of getgauge that we're using (this is with gauge 0.9.8) - 

BEGIN>> 
[06/06 07:41:17] normanja@PC602153:~/dorado-acceptance-tests$ time gauge run --verbose specs-test/001_short_test.spec 
Python: 2.7.15rc1 
# Short Test 
## Should not fail 
* Bad character in Python file ...[FAIL] 

Failed Step: Bad character in Python file 
Specification: specs-test/001_short_test.spec:8 
Error Message: 'NoneType' object is not callable 
Stacktrace: 
Traceback (most recent call last): 
File "/home/normanja/.local/lib/python2.7/site-packages/getgauge/executor.py", line 31, in execute_method 
func(*params) 
TypeError: 'NoneType' object is not callable 


Successfully generated html-report to => /home/normanja/dorado-acceptance-tests/reports/html-report/index.html 
Specifications: 1 executed 0 passed 1 failed 0 skipped 
Scenarios: 1 executed 0 passed 1 failed 0 skipped 

Total time taken: 707ms 

real 0m11.364s 
user 0m10.068s 
sys 0m0.409s 
[06/06 07:41:33] normanja@PC602153:~/dorado-acceptance-tests$ pip list|grep getgauge 
getgauge 0.3.2 
[06/06 07:41:49] normanja@PC602153:~/dorado-acceptance-tests$ 
END>>

**Comment by BugDiver** [comment]
@opendragon  Thanks for giving the info. We are able to replicate your issue but it's only replicable on python2.
My guess is it is related to the encoding issue in python2.
Could you please try adding  `# -*- coding: utf-8 -*-` in the top of your implementation file which contains the NON-ASCII character?

**Comment by opendragon** [comment]
Hi: 
That fixed the problem... what is weird is that older versions of gauge (specifically 0.8.3, which we've been using for months...) did not have this issue. 
However, we were also using getgauge 0.2.0 at the same time...

**Comment by NivedhaSenthil** [comment]
The issue seems to happen from 0.2.5, before which it was fine. Need to check what broke it.

**Comment by NivedhaSenthil** [comment]
The python step script was compiled using py_compile earlier which was changed from 0.2.3 to 0.2.5, since it is not needed as we are also importing the step in gauge-python. The compilation had handled encoding earlier. Since the removal of compilation is a valid fix, 
it is better to use  `# -*- coding: utf-8 -*-` to tell explicitly that utf-8 encoding is used.
