### ISSUE TITLE
Should not get GET and POST event logs

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-python#91]
### Description
When gauge tests are run should not get the GET and POST event logs

### Steps to reproduce
1. `gauge init python_selenium`
2. `gauge run specs`
> The events are displayed

### Information that will help us debug
```
Gauge version: 1.0.1.nightly-2018-07-09
Commit Hash: 72109fa

Plugins
-------
python (0.3.4.nightly-2018-07-10)
```

**Comment by BugDiver** [comment]
The fix should be available in nightly >= 17-07-2018
