### ISSUE TITLE
Proposal for a simplified data store API

### ISSUE THREAD

**Issue by surajbarkale** [getgauge/gauge-python#93]
### Description
The current data store API seems to be inspired by Java and does not feel very pythonic. A simple `dict` access would better suit python code.

Implementation in getgauge/python.py can be:
```python
class DataStoreContainer:
    def __init__(self):
        self.__scenario = dict()
        self.__spec = dict()
        self.__suit = dict()

    @property
    def scenario(self):
        return self.__scenario

    @property
    def spec(self):
        return self.__spec

    @property
    def suit(self):
        return self.__suit


data_store = DataStoreContainer()
```

It can be used in step as follows:
```python
from getgauge import step, data_store

@step("description")
def step_fn():
	value = data_store.scenario['key']
```

This API can also be made backwards compatible through existing `DataStoreFactory` interface.

**Comment by sriv** [comment]
Hi @surajbarkale - thank you for the suggestion.  This looks neat.

Would you like to send us a Pull Request?

**Comment by BugDiver** [comment]
This issue still needs testing.

**Comment by BugDiver** [comment]
The fix Should be available in nightly >= 19 July 2018

**Comment by sguptatw** [comment]
Documentation should be updated with the recommended usage.

**Comment by BugDiver** [comment]
The documentation is already updated. Refer https://github.com/getgauge/docs.gauge.org/pull/85
