### ISSUE TITLE
steps file are opened with read+write permissions.

### ISSUE THREAD

**Issue by aasim** [getgauge/gauge-python#97]
### Description
The load_files function in static_loader.py reads python files using the "r+" access mode. This should be just "r" since the file is not written into.

### Steps to reproduce
1. Mount the steps_impl_dir as a readonly directory with all python files with read-only permissions for the runAs user.
2. Run gauge run specs/
3. The command fails as it is unable to read the steps_impl_dir correctly.

### Information that will help us debug

* Gauge version: 1.0.0
* Gauge Python plugin version: 0.3.3
* Python version: 3.6
* `getgauge` package version, run `pip3 show getgauge` to get it: 0.3.3
* OS information: library/python:3.6 docker (Ubuntu)

Plugins
-------
html-report (4.0.4)
json-report (0.2.2)
python (0.3.3)
screenshot (0.0.1)

**Comment by BugDiver** [comment]
The fix should be available in nightly >= 01-08-2018.

**Comment by sguptatw** [comment]
**Verified in**
```
Gauge version: 1.0.1.nightly-2018-07-31
Commit Hash: 4ae7c9a

Plugins
-------
python (0.3.4.nightly-2018-07-25)
```
